#!/usr/bin/env bash
#Bash script that displays Best School 10 times,after 9 Hi
i=10
while [ $i -ge 0 ]
do
    if [ $i -eq 1 ]
    then 
	echo 'Hi'
    else 
      echo 'Best School'
    fi
    i=$((i - 1))case 
done
